spring.application.name=demo
google.books.base-url=https://www.googleapis.com/books/v1
google.books.api-key=AIzaSyCyAnMCjczRUWppOBOtMGmQTRdOo7xULww
#You need to add your own API key from Google Books API to make it work.
#I am not adding it here for security reasons.
# You can get your API key from https://developers.google.com/books/docs/v1/using#APIKey



